stages:
- install-deps
- format-check

deps:
  image: python:3.10
  stage: install-deps
  script:
    - pip install poetry
    - poetry install

format:
  stage: format-check
  needs:
    - deps
  script:
    - poetry run ruff format --check .
    - poetry run ruff check .
    # - coverage run -m pytest --verbose
    # - find . -type f -name "*.py" | xargs -t coverage report
